version: '3.7'
services:
  tel-boot-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      app_logging: info
      api_http_ip: 0.0.0.0
      api_http_port: 5001
    restart: always