version: '3.7'
services:
  tel-boot-service:
    image: pavhov/tel-boot-service:latest
    environment:
      app_logging: info
      api_http_ip: 0.0.0.0
      api_http_port: 80

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.api.rule=Host(`tel-boot.4fv.pl`)"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.routers.api.service=api-tel-boot"
        - "traefik.http.services.api-tel-boot.loadbalancer.server.port=80"
        - "traefik.http.services.api-tel-boot.loadbalancer.server.scheme=http"

      placement:
        - "node.role==manager"
        - "node.labels.tag==main"
    networks:
      - "traefik"


networks:
  traefik:
    external: true
    driver: "overlay"
